version: '3.8'

services:
  app:
    container_name: nestjs-app
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - '6379:6379'
    restart: always

volumes:
  pgdata:
